/* Gigly — real scheme data drawn from the research brief.
   Figures are the actual headline numbers from Indian govt + aggregator schemes. */

window.APP_DATA = {
  // ───────────────────────── RIGHTS ─────────────────────────
  // Each right has full plain-language detail for the guide screen.
  rights: [
    {
      id: 'eshram',
      title: 'e-Shram Card',
      issuer: 'Ministry of Labour & Employment',
      category: 'Identity',
      headline: '₹2,00,000',
      headlineNote: 'accident cover + unlocks 14 schemes',
      valueNum: 200000,
      kind: 'foundation',
      tagline: 'Your universal worker ID. The key to everything else.',
      featured: true,
      summary: 'A free, 12-digit Aadhaar-linked ID that officially recognises you as a worker. It makes your benefits portable — they follow you across Swiggy, Zomato, Uber or any platform, and across states. Registering also switches on 14 pre-mapped government schemes automatically.',
      premium: 'Free — no cost to register',
      eligibility: [
        'Aged 16–59 years',
        'Working in the unorganised sector (gig & platform work counts)',
        'Not a member of EPFO or ESIC',
        'Have an Aadhaar number and a linked mobile number',
      ],
      documents: [
        'Aadhaar card',
        'Mobile number linked to Aadhaar',
        'Bank account number & IFSC code',
      ],
      steps: [
        'Open the e-Shram self-registration portal',
        'Enter your Aadhaar-linked mobile number and verify the OTP',
        'Fill in your work type, address and bank details',
        'Download your e-Shram card instantly — your UAN is generated on the spot',
      ],
      portal: 'eshram.gov.in',
      portalUrl: 'https://eshram.gov.in',
    },
    {
      id: 'pmsby',
      title: 'PM Suraksha Bima Yojana',
      issuer: 'Govt. of India · PMSBY',
      category: 'Insurance',
      headline: '₹2,00,000',
      headlineNote: 'accidental death & disability',
      valueNum: 200000,
      tagline: 'Accident cover for the price of a cup of chai.',
      summary: 'A government-backed accident insurance scheme. If you suffer an accidental death or full disability, your family receives ₹2 lakh. Partial disability is covered up to ₹1 lakh. The premium is auto-debited once a year from your bank account.',
      premium: '₹20 per year — auto-debited',
      eligibility: [
        'Aged 18–70 years',
        'Hold a savings or Jan Dhan bank account',
        'Account must be linked to Aadhaar',
        'Give one-time consent for the annual auto-debit',
      ],
      documents: [
        'Aadhaar card',
        'Aadhaar-linked savings / Jan Dhan account',
        'Nominee details',
      ],
      steps: [
        'Visit your bank branch or net-banking portal',
        'Fill the PMSBY consent-cum-declaration form',
        'Authorise the ₹20 annual auto-debit',
        'Save your acknowledgement — cover is active immediately',
      ],
      portal: 'jansuraksha.gov.in',
      portalUrl: 'https://www.jansuraksha.gov.in',
    },
    {
      id: 'pmjjby',
      title: 'PM Jeevan Jyoti Bima Yojana',
      issuer: 'Govt. of India · PMJJBY',
      category: 'Insurance',
      headline: '₹2,00,000',
      headlineNote: 'life cover, any cause of death',
      valueNum: 200000,
      tagline: 'Life cover so your family is never left stranded.',
      summary: 'A term life insurance scheme that pays your nominee ₹2 lakh on your death from any cause. One of the most affordable life covers in India, renewed yearly through a simple bank auto-debit.',
      premium: '₹436 per year — auto-debited',
      eligibility: [
        'Aged 18–50 years (cover continues to 55)',
        'Hold a savings or Jan Dhan bank account',
        'Account linked to Aadhaar',
        'Note: claims have a 30-day waiting period from joining',
      ],
      documents: [
        'Aadhaar card',
        'Aadhaar-linked savings account',
        'Nominee name & relationship',
      ],
      steps: [
        'Approach your bank branch or use net-banking',
        'Complete the PMJJBY enrolment form',
        'Consent to the ₹436 annual premium auto-debit',
        'Keep your certificate of insurance safe for your nominee',
      ],
      portal: 'jansuraksha.gov.in',
      portalUrl: 'https://www.jansuraksha.gov.in',
    },
    {
      id: 'pmsym',
      title: 'PM Shram Yogi Maan-Dhan',
      issuer: 'Govt. of India · PM-SYM',
      category: 'Pension',
      headline: '₹3,000',
      headlineNote: 'guaranteed monthly pension at 60',
      valueNum: 0,
      isPension: true,
      tagline: 'A pension for your future self. Government matches every rupee.',
      summary: 'A voluntary pension scheme built for unorganised workers. You contribute a small amount each month and the government matches it rupee-for-rupee. From age 60, you receive an assured ₹3,000 every month for life. If you pass away, your spouse receives 50%.',
      premium: '₹55–₹200/month (by age) · govt matches 50%',
      eligibility: [
        'Aged 18–40 years',
        'Monthly income of ₹15,000 or less',
        'Not a member of EPFO, ESIC or NPS',
        'Have a savings / Jan Dhan account and Aadhaar',
      ],
      documents: [
        'Aadhaar card',
        'Savings / Jan Dhan account with IFSC',
        'Mobile number',
      ],
      steps: [
        'Visit your nearest Common Service Centre (CSC)',
        'Share your Aadhaar and bank details for enrolment',
        'Choose your monthly contribution based on your age',
        'Your first instalment is paid in cash; future ones auto-debit',
      ],
      portal: 'maandhan.in',
      portalUrl: 'https://maandhan.in',
    },
    {
      id: 'pmjay',
      title: 'Ayushman Bharat — PM-JAY',
      issuer: 'National Health Authority',
      category: 'Health',
      headline: '₹5,00,000',
      headlineNote: 'family health cover per year',
      valueNum: 500000,
      tagline: 'Cashless hospital care for your whole family.',
      featured: true,
      summary: 'The world\'s largest health-assurance scheme. It covers up to ₹5 lakh per family per year for hospitalisation — fully cashless at empanelled hospitals. Budget 2025-26 is bringing over 1 crore platform delivery & driver partners directly into this scheme.',
      premium: 'Free — fully government-funded',
      eligibility: [
        'Gig & platform workers registered on e-Shram',
        'Covers the whole family — no cap on family size',
        'No restriction on age or pre-existing conditions',
        'Valid at any empanelled hospital, public or private',
      ],
      documents: [
        'e-Shram card / Aadhaar',
        'Ration card or family ID (for family linking)',
      ],
      steps: [
        'Check your eligibility on the PM-JAY portal or app',
        'Visit an empanelled hospital\'s Ayushman Mitra desk',
        'Verify your identity with Aadhaar',
        'Get your Ayushman card and access cashless treatment',
      ],
      portal: 'pmjay.gov.in',
      portalUrl: 'https://pmjay.gov.in',
    },
    {
      id: 'zomato',
      title: 'Zomato Partner Cover',
      issuer: 'Zomato · activates on onboarding',
      category: 'Platform',
      headline: '₹10,00,000',
      headlineNote: 'accident cover, on by default',
      valueNum: 1000000,
      platforms: ['Zomato', 'Blinkit'],
      tagline: 'Already yours the moment you start delivering.',
      summary: 'Active delivery partners are covered by default. Up to ₹10 lakh for accidental death or disability, ₹1 lakh medical cover with a ₹5,000 OPD allowance, ₹50,000 loss-of-pay support, plus maternity cover up to ₹40,000 and two paid period rest-days a month.',
      premium: 'Free — paid by Zomato',
      eligibility: [
        'Active Zomato or Blinkit delivery partner',
        'Cover activates automatically on onboarding',
        'Most benefits apply while logged in / on an order',
        'Maternity & rest-day benefits for women partners',
      ],
      documents: [
        'Zomato partner ID',
        'Bank account on file for claim payout',
      ],
      steps: [
        'Open the Zomato Delivery Partner app',
        'Go to Profile → Insurance & Benefits',
        'Review your active cover and add nominee details',
        'Raise a claim in-app with photos and documents if needed',
      ],
      portal: 'Zomato Partner app',
      portalUrl: 'https://www.zomato.com',
    },
    {
      id: 'swiggy',
      title: 'Swiggy Suraksha',
      issuer: 'Swiggy · IndusInd General Insurance',
      category: 'Platform',
      headline: '₹1,00,000',
      headlineNote: 'health + accident, scales with hours',
      valueNum: 100000,
      platforms: ['Swiggy', 'Swiggy Instamart'],
      tagline: 'Your engagement unlocks bigger cover.',
      summary: 'A tiered safety net for active Swiggy partners: health insurance, personal accident and accidental-death cover, plus ₹5,000 mobile-phone insurance. The more you deliver, the more your cover grows — up to ₹1 lakh hospitalisation, spouse maternity cover and three months loss-of-pay. Free on-demand ambulance and in-app SOS too.',
      premium: 'Free — paid by Swiggy',
      eligibility: [
        'Active Swiggy delivery partner',
        'Base cover for all; higher tiers by engagement & hours',
        'Free ambulance for partner + immediate family',
        'In-app SOS routes to local police & emergency services',
      ],
      documents: [
        'Swiggy partner ID',
        'Bank account & nominee on file',
      ],
      steps: [
        'Open the Swiggy Delivery app',
        'Go to Suraksha → Insurance & Safety',
        'Check your current tier and what unlocks the next one',
        'Use the quick-fix claims flow for instant non-network payouts',
      ],
      portal: 'Swiggy Delivery app',
      portalUrl: 'https://www.swiggy.com',
    },
  ],

  categories: ['All', 'For You', 'Identity', 'Insurance', 'Health', 'Pension', 'Platform'],

  // ───────────────────────── FORUM ─────────────────────────
  forumTabs: ['Trending', 'Near Me', 'My Company'],
  forumTags: ['Document Help', 'E-Shram', 'Payments', 'Health', 'Safety', 'Tips', 'Pension'],
  posts: [
    {
      id: 'p1',
      author: 'Ramesh Kumar', handle: '@ramesh_dxb', initials: 'RK', color: '#0F766E',
      location: 'Delhi NCR', company: 'Swiggy',
      text: 'Anyone managed to link e-Shram with their Swiggy ID? Mine keeps showing an Aadhaar name-mismatch error. Did you fix it at a CSC centre?',
      tags: ['Document Help', 'E-Shram'],
      upvotes: 47, comments: 12, time: '2h', solved: false,
    },
    {
      id: 'p2',
      author: 'Priya Sharma', handle: '@priya_uc', initials: 'PS', color: '#F97316',
      location: 'Mumbai', company: 'Urban Company',
      text: 'Good news — UC Plus health cover now includes spouse + 2 kids under the ACKO policy. Claim got settled cashless in under an hour. Sharing the steps below 👇',
      tags: ['Health', 'Tips'],
      upvotes: 89, comments: 23, time: '5h', solved: true,
    },
    {
      id: 'p3',
      author: 'Imran Sheikh', handle: '@imran_blr', initials: 'IS', color: '#0F766E',
      location: 'Bengaluru', company: 'Uber',
      text: 'Under the new Karnataka law aggregators must give 14 days notice before deactivating you. If you were dropped without a reason, you can file with the Welfare Board. Has anyone tried this yet?',
      tags: ['Payments', 'Tips'],
      upvotes: 134, comments: 41, time: '8h', solved: false,
    },
    {
      id: 'p4',
      author: 'Lakshmi Devi', handle: '@lakshmi_hyd', initials: 'LD', color: '#F97316',
      location: 'Hyderabad', company: 'Zomato',
      text: 'PMSBY is genuinely just ₹20 a year for ₹2 lakh accident cover. Took me 10 minutes at the bank. Please do this for your family, brothers and sisters.',
      tags: ['Tips'],
      upvotes: 212, comments: 56, time: '1d', solved: false,
    },
    {
      id: 'p5',
      author: 'Arjun Nair', handle: '@arjun_ncr', initials: 'AN', color: '#0F766E',
      location: 'Delhi NCR', company: 'Zomato',
      text: 'Which documents do I need for the PM-SYM pension? The CSC person asked for income proof but I do not have a salary slip. What did you all show?',
      tags: ['Document Help', 'Pension'],
      upvotes: 38, comments: 17, time: '1d', solved: false,
    },
  ],

  // current signed-in user (post-onboarding default)
  user: { name: 'You', initials: 'YO', location: 'Delhi NCR', company: 'Swiggy' },
};
